### PR TITLE
🚑 Add suicide option to kill process periodically

### PR DESCRIPTION
**Pull request by nnkken**

### CODE REVIEW

**Comment by williamchong007** [comment]
make a restful endpoint for killing itself, then trigger by some ex/internal cron/scheduled pub/sub job?
it would be funny if the suicide timer itself did not trigger due to some timer error

**Comment by nnkken** [comment]
Should the RESTful endpoint reply gracefully before process suicide?
If so, then we need some timer before `process.exit`, which goes back to the timer failure problem.

**Comment by williamchong007** [comment]
just try to reply 200/500(not sure which) then exit i suppose
Set a very short timeout on the cron to prevent waiting for too long

**Comment by nnkken** [comment]
Force pushed.
The `res.sendStatus` surprisingly works well, being able to send the response before process exit.
Do we need any auth for the endpoint?

**Comment by williamchong007** [comment]
ask @mckingho if he have any magic cron method to fire this hook in k8s internally?

**Comment by nnkken** [comment]
Or just set some secret in config for auth?

**Comment by williamchong007** [comment]
even with auth we would prefer internal calling
make it only check for auth if such config exists i guess

**Pull request merged**
